### ISSUE TITLE
Tried to get the code and compile it but failed

### ISSUE THREAD

**Issue by JohnnyBeAwesome** [sshaerosol/ssh-aerosol#1]
Hello, 

I downloaded the and tried to compile it but got the following error:

scons: *** [include/Talos/_talos.so] Source file: include/Talos/talos.i is static and is not compatible with shared target: include/Talos/_talos.so

After a while I managed to compile the code, but I had to change :

env.SharedLibrary('_talos.so', ['Talos.cpp', 'talos.i'])
into:
env.StaticLibrary('_talos.so', ['Talos.cpp', 'talos.i'])

in src/include/Talos/SConstruct

I am not a huge specialist of the concept of shared and static library, so I am not quite sure it is a good thing to do. Do you think it might be my configuration (hardware, software) that might be the origin of my problem?

Best regards, 
Jonathan

**Comment by mathrack** [comment]
Hello Jonathan,

You are probably missing the dependency swig.

Best regards,
Cédric

**Comment by JohnnyBeAwesome** [comment]
Dear Cédric, 

thank you for your quick answer. It was indeed a swig dependency problem. I managed to get a proper compilation without having to mess with the library settings.

Best, 
Jonathan
